import { ThemeProvider } from "@/context/theme-provider";
import MainNav from "@/components/main-nav";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import { HydrateClient } from "@/components/hydrate-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mini E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <HydrateClient />
          <MainNav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
